<a href="https://colab.research.google.com/github/nanaso-mane/AI_Training/blob/main/ml_regression_insurance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy  as np
import pandas as pd

In [2]:
data=pd.read_csv('/content/insurance - practice.csv')

In [3]:
data.head()

age     sex   bmi  children smoker     region  expenses
0   19  female  27.9         0    yes  southwest  16884.92
1   18    male  33.8         1     no  southeast   1725.55
2   28    male  33.0         3     no  southeast   4449.46
3   33    male  22.7         0     no  northwest  21984.47
4   32    male  28.9         0     no  northwest   3866.86

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1338 non-null   int64  
 1   sex       1338 non-null   object 
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64  
 4   smoker    1338 non-null   object 
 5   region    1338 non-null   object 
 6   expenses  1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB


In [6]:
data['sex'].unique()

array(['female', 'male'], dtype=object)

In [7]:
data['smoker'].unique()

array(['yes', 'no'], dtype=object)

In [8]:
data['region'].unique()

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

In [9]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [10]:
data['sex']=le.fit_transform(data['sex'])

In [12]:
data['sex'].unique()

array([0, 1])

In [13]:
data['smoker']=le.fit_transform(data['smoker'])

In [14]:
data['smoker'].unique()

array([1, 0])

In [15]:
data['region']=le.fit_transform(data['region'])

In [16]:
data['region'].unique()

array([3, 2, 1, 0])

In [17]:
data.head()

age  sex   bmi  children  smoker  region  expenses
0   19    0  27.9         0       1       3  16884.92
1   18    1  33.8         1       0       2   1725.55
2   28    1  33.0         3       0       2   4449.46
3   33    1  22.7         0       0       1  21984.47
4   32    1  28.9         0       0       1   3866.86

In [18]:
x=data[['age',	'sex',	'bmi',	'children',	'smoker',	'region']]
y=data['expenses']

In [19]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x, y, train_size=0.70)

In [20]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()

In [21]:
model.fit(x_train, y_train)

LinearRegression()

In [22]:
predictions = model.predict(x_test)

In [23]:
model.score(x, y)

0.7501868078113387